---
title: "ph1855_hw3_ygu5"
author: "Yue Gu"
date: "2024-02-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(agricolae)
library(NSM3)
library(tidyverse)
```

# Hollander et al. Nonparametric Statistical Methods-Chapter 4
# P133 Q1
```{r}
qnorm(0.95) #1.645
```

# P135 Q15
```{r}
1-pnorm(2.27)
```

# P136 Q16
```{r}
# read data
noninjured = c(.19, .14, .02, .44, .37)
iSCI = c(.89, .76, .63, .69, .58, .79, .02, .79)

wilcox.test(c(noninjured, iSCI)~factor(c(0,0,0,0,0, 1,1,1,1,1,1,1,1)))

```

# P136 Q17
```{r}
noninjured = c(.19, .14, .02, .44, .37, 0, 0, 0)
iSCI =       c(.89, .76, .63, .69, .58, .79, .02, .79)

#install.packages("agricolae")
library(agricolae)
results = waerden.test(iSCI, noninjured)
results
```

# P141 Q18
```{r}
# input nonallergics (baseline) vs allergics
X =  c(48.1, 48.0, 45.5, 41.7, 35.4, 34.3, 32.4, 29.1, 27.3, 18.9, 6.6, 5.2, 4.7)
Y =  c(1651.0, 1112.0, 102.4, 100.0, 67.6, 65.9, 64.7, 39.6, 31.0)
# store the difference
n = 9
m = 13
diff = NULL

for (i in 1:m){ 
  for (j in 1:n){ 
    diff = c(diff, X[i]-Y[j])
}
  }
# sort the difference by increasing order
sort(diff)[59]
# check output from the test results
wilcox.test(X, Y, conf.int = T)
```

# P144 Q30
```{r}
X =  c(48.1, 48.0, 45.5, 41.7, 35.4, 34.3, 32.4, 29.1, 27.3, 18.9, 6.6, 5.2, 4.7)
Y =  c(1651.0, 1112.0, 102.4, 100.0, 67.6, 65.9, 64.7, 39.6, 31.0)
wilcox.test(X, Y, conf.int = T, conf.level = 0.95)
```


# P145 Q35
```{r}
X =  c(48.1, 48.0, 45.5, 41.7, 35.4, 34.3, 32.4, 29.1, 27.3, 18.9, 6.6, 5.2, 4.7)
Y =  c(1651.0, 1112.0, 102.4, 100.0, 67.6, 65.9, 64.7, 39.6, 31.0)
# store the difference
n = 9
m = 13
diff = NULL

for (i in 1:m){ 
  for (j in 1:n){ 
    diff = c(diff, X[i]-Y[j])
}
  }

# find the number of position 29 and 89
sort(diff)[29]
sort(diff)[89]

# compare with Q20
wilcox.test(X, Y, conf.int = T, conf.level = 0.95)
```

# P149 Q43
```{r}
X =  c(48.1, 48.0, 45.5, 41.7, 35.4, 34.3, 32.4, 29.1, 27.3, 18.9, 6.6, 5.2, 4.7)
Y =  c(1651.0, 1112.0, 102.4, 100.0, 67.6, 65.9, 64.7, 39.6, 31.0)

library(NSM3)
pFligPoli(X, Y)
```


